version: "2.3"

services:

  unprotected-server:
    image: approov/golang:1.18
    build: ./
    networks:
      - default
    command: bash -c "go run hello-server-unprotected.go"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/unprotected-server:/home/developer/workspace

  approov-token-check:
    image: approov/golang:1.18
    build: ./
    networks:
      - default
    command: bash -c "go run hello-server-protected.go"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-check:/home/developer/workspace

  approov-token-binding-check:
    image: approov/golang:1.18
    build: ./
    networks:
      - default
    command: bash -c "go run hello-server-protected.go"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-binding-check:/home/developer/workspace

