services:
  approov-server:
    image: approov/golang:1.18
    build: ./
    env_file:
      - ./.env
    networks:
      - default
    command: go run server.go
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8111}:${HTTP_PORT:-8111}
    volumes:
      - ./:/home/developer/workspace
    working_dir: /home/developer/workspace

